config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :books do
    resources :ratings
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :ratings, dependent: :destroy
  has_one_attached :resume
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  validates :author, presence: true
  validates :publishing_year, presence: true
  # validate :resume_attached?

  belongs_to :user
  def average_rating
    return 0 if ratings.empty?

    (ratings.map(&:rating).sum / ratings.count).round 2
  end

  def resume_attached?
    return errors.add(:resume, "must add an resume") unless resume.attached?
  end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
  validates :rating, inclusion: { in: 0..5 }, numericality: true
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  has_one_attached :attachment
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_after_action :verify_authorized, except: :index, unless: :skip_pundit?
  skip_after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR author ILIKE :query"
      @books = Book.where(sql_query, query: "%#{params[:query]}%")
    else
      @books = policy_scope(Book).order(created_at: :desc)
    end
  end

  def show
    @book = Book.find(params[:id])
    @review = Review.new
    @reviews = Review.all.where(book_id: @book.id)
  end

  def new
    authorize @book = Book.new
  end

  def edit
    authorize @book = Book.find(params[:id])
  end

  def create
    authorize @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def update
    authorize @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      # @book.errors
      render :new
    end
  end

  def destroy
    authorize @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :publishing_year, :resume, :user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    # write something
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
 skip_after_action :verify_authorized, except: :index, unless: :skip_pundit?
 skip_after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  def new
    @book = Book.find(params[:book_id])
    @rating = Rating.new
  end

  def edit
    # @rating = Rating.find(params[:book_id])
  end

  def create
    @book = Book.find(params[:book_id])
    @rating = Rating.new(rating_params)
    @rating.book = @book
    if @rating.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def update
    # @rating = Rating.find(params[:book_id])
    # @rating.update(rating_params)
    # redirect_to ratings_path(@rating)
  end

  private

  def rating_params
    params.require(:rating).permit(:rating, :book_id)
  end
end

app/controllers/reading_lists_controller.rb
class ReadingListsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    authorize @book = Book.find(params[:book_id])
    authorize @review = Review.new
  end

  def create
    @book = Book.find(params[:book_id])
    authorize @review = @book.reviews.new(review_params)
    @review.save!
    redirect_to book_path(@book)
  end

  def edit
    find_review
  end

  def update
    find_review
    @review.update(review_params)
  end

  def destroy
    find_review
    @review.destroy
  end

  private

  def find_review
    authorise @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :author, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= simple_form_for [@book] do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :publishing_year %>
  <%= f.input :resume, required: true %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<%= render 'form', book: @book %>

app/views/books/index.html.erb
<div class="container-main">
  <div class="index_banner d-flex flex-column align-items-center">
       <h1 class="title_library">BOOKS LIBRARY</h1>
       <div class="container">
          <div class="row">
            <% @books.first(8).each do |book| %>
             <div class="card d-flex flex-column align-items-center istvan">
                <img class= "image-card" src="https://softcover.s3.amazonaws.com/636/ruby_on_rails_tutorial_6th_edition/images/cover-web.png" alt="book-cover" style="width:250px;height:200px;">
              <div class="card-book-info d-flex flex-row justify-content-between align-items-center">
                <div class="d-flex flex-column justify-content-start card-infos">
                  <h2 class="card-book-title"><%= book.title %></h2>
                  <div class="christophe d-flex flex-row justify-content-between align-items-center">
                    <h4 class="card-book-author"><%= book.author %></h4>
                      <h7 id="star">⭐ <%= book.average_rating %></h7 id="star">
                    <% if policy(book).show? %>
                      <p><%= link_to "Details", book_path(book), class: 'btn-details' %></p>
                    <% end %>
                </div>
                </div>
              </div>
             </div>
            <% end %>
          </div>
       </div>
       <% if policy(Book).new? %>
          <%= link_to "Create a New Book?", new_book_path, class: 'btn-details2' %>
       <% end %>
  </div>

  <% if !flash[:notice].blank? %>
     <div class = "alert alert-info">
        <%= flash[:notice] %>
     </div>

  <% end %>

</div>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<div class="container-main2">
  <div class="banner-small">
    <img src="https://images.unsplash.com/photo-1519682337058-a94d519337bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="All the Books You Need">
    <div class="txt-ban">
      <h2><strong>KNOW-BOOK</strong></h2>
      <h5>The best App for any student who wishes to have their books at hand at any time.</h5>
      <br>
      <p class="btn button-medium-small"><%= link_to "All books", books_path %></p>
    </div>
  </div>
  <div class="container-show">
    <div class="container-left">
      <div class="card-book">
        <div class="img-book">
          <img src="https://www.perlego.com/books/RM_Books/pearson_lm/9781292256047.jpg" alt="Some descritpion">
          <% if @book.resume.attached? %>
            <%= link_to "PDF", url_for(@book.resume) %>
          <% else %>
            <p>"You have not uploaded a pdf"</p>
          <% end %>
        </div>
        <div class="btn-show">
          <p id="reading_list" class="btn button-show"><%= link_to "Add to reading list - Available Soon..! -", book_path %></p>
        </div>
          <br>
        <div class="book-content column">
          <p><%= rand(500..1500) %> pages</p>
          <p>English</p>
          <p>PDF</p>
        </div>
      </div>
    </div>

    <div class="container-right">
      <div class="card-description">
        <div>
          <h1 class="title"><%= @book.title %></h1>
          <h2 class="author"><%= @book.author %></h2>
            <br>
          <p class="info">Year: <%= @book.publishing_year%> --  Rating: <%= @book.average_rating %></p>
        </div>
          <br>
        <div>
          <h2><strong>About This Book</strong></h2>
            <br>
          <p>The 19th edition of this market-leading text provides a comprehensive overview of financial accounting and reporting, with the aim of ensuring you are able to prepare and also critically discuss IFRS compliant financial statements. With balanced coverage of theoretical principles and up-to-date practical application of current international standards, the authors provide essential knowledge for advancing your studies and career.</p>
          <a>Read More</a>
        </div>
        <br>
        <div id="buttons-descr">
          <p class="btn button-show"><%= link_to "Add a Rating", new_book_rating_path(@book) %></p>
        </div>
        <br>
        <div class="reviews-container">
          <% @reviews.each do |review| %>
            <div class="review card">
              <%= review.content %>
              <br>
              <br>
              --<%= User.find(@book.user_id).username.upcase %>
            </div>
          <% end %>
        </div>
        <div class="review-form">
          <%= simple_form_for [@book, @review] do |f| %>
            <%= f.input :content %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </div>
        <div>
      </div>
    </div>

    <div>
      <% if policy(@book).destroy? %>
          <p class="btn btn-show"><%= link_to "Delete Book", book_path, method: :delete, data: { confirm: "Are you Sure about Deleting this Book?" } %></p>
        <% end %>

        <% if policy(@book).edit? %>
          <p class="btn btn-show"><%= link_to "Edit Book", edit_book_path(@book) %></p>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap" rel="stylesheet">
    <title>Lex-It!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
    <body>
      <% unless devise_controller? %>
        <%= render 'shared/navbar' %>
      <% end %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <% unless devise_controller? || action_name == 'show' && controller_name == 'books'%>
      <%= render 'shared/footer' %>
      <% end %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
    </body>
</html>

app/views/pages/home.html.erb
      <div class="container-banner">
        <img src="https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=541&q=80" alt="Online Book Library" id="background-image">
        <div class="title-ban">

          <h1><em>Know-Book</em></h1>
          <br>

          <h3>Every Student's Dream App</h3>
          <br>

          <p>The first <strong>interactive</strong>, <strong>connected</strong> and <strong>centralised</strong> App where you will be able to access all your Academic Books, Class Notes and Topic-Related News.</p>

          <p class="button-medium"><%= link_to "Browse your Library", books_path %></p>
        </div>
      </div>

app/views/ratings/edit.html.erb
<h1>Ratings#edit</h1>
<p>Find me in app/views/ratings/edit.html.erb</p>

app/views/ratings/new.html.erb
<%= simple_form_for [@book, @rating] do |f| %>
  <%= f.input :rating %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<%= simple_form_for [@book, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :author, :input_hmtl => { :value => current_user } %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="text-center" id="footer">
    <div class="row mt-3 dark-grey-text">
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">
        <h6 class="text-uppercase font-weight-bold">KNOW-BOOK</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Download and read any book you want on KNOW-BOOK !</p>

      </div>
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <h6 class="text-uppercase font-weight-bold">Library</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">All books</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">My books</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">My favourites</a>
        </p>
      </div>

      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <h6 class="text-uppercase font-weight-bold">Contact us</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Cantersteen 10, 1000 Brussels, Belgium</p>
        <p>
          <a href="mailto:info@knowbook.com?subject=need help"><i class="fas fa-envelope mr-3"></i> info@knowbook.com</a></p>
        <p>
          <i class="fas fa-phone mr-3"></i> +32 476 52 52</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center text-black-50 py-3">© 2019 Copyright:
    <a class="dark-grey-text" href="#"> KNOW-BOOK.com</a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-space-between">
  <div>
    <a class="navbar-brand" href="#">
      <%= link_to root_path do  %>
        <%= image_tag("logo_knowbook.png", width: 70 , alt: "alttext") %>
      <% end %>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
     <!--  <% if user_signed_in? %>
          <%= link_to "All Books", books_path, class: "nav-link" %>
      <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %> -->
    </ul>
  </div>
  <form class="form-inline">
    <%= form_tag books_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a book"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </form>
  <div class="avatar-spot">
    <% if user_signed_in? %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
    <% end %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "My Books", "#", class: "dropdown-item" %>
            <%= link_to "My Favourites", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
  </div>
</nav>